name: fond_check
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  http: ^1.2.2
  intl: ^0.20.1
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
